[package]
name = "drift-gui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
drift-app.workspace = true
drift-core.workspace = true
tokio-util.workspace = true
tokio.workspace = true
gpui-kit.workspace = true

[dev-dependencies]
rustls.workspace = true
tempfile.workspace = true
gpui-kit = { workspace = true, features = ["test-support"] }

[lints]
workspace = true
