use gpui_kit::{App, KeyBinding};

gpui_kit::actions!(
    drift,
    [
        FocusFilter,
        FocusResults,
        TogglePreview,
        FocusPreview,
        CopyPreview,
        ShowHelp,
        CancelWork,
        CopySelection,
        DiffCaretLeft,
        DiffCaretRight,
        DiffSelectLeft,
        DiffSelectRight,
        DiffSelectUp,
        DiffSelectDown,
        DiffSelectStart,
        DiffSelectEnd,
        DiffSelectAll,
        Refresh,
        Cancel,
        GoUp,
        GoBack,
        GoForward,
        CursorUp,
        CursorDown,
        CursorFirst,
        CursorLast,
        PageUp,
        PageDown,
        HalfPageUp,
        HalfPageDown,
        ScrollUp,
        ScrollDown,
        ExpandContext,
        FoldContext,
        ToggleFolds,
        Upload,
        Download,
        CycleAll,
        SwitchPane,
        ResizePaneLeft,
        ResizePaneRight,
        ResetPaneSizes,
        ShowProjects,
        ShowHosts,
        ShowRemote,
        FindFiles,
        ReturnFromFinder,
        ToggleHidden,
        ToggleIgnored,
        NextFile,
        PreviousFile,
        SyncSelected,
        SyncAll,
        ConfirmSync,
        ToggleSyncErrors,
        Activate,
        Collapse,
        OpenDirectory,
        OpenContextMenu,
        NextHunk,
        CompareMarked,
        ToggleMark,
        VisualRange,
        MarkAll,
        InvertMarks,
        ClearMarks,
        RangeUp,
        RangeDown,
        PreviousHunk
    ]
);
pub fn bind_keys(cx: &mut App) {
    crate::hosts::bind_keys(cx);
    crate::projects::bind_keys(cx);
    crate::certificates::bind_keys(cx);
    cx.bind_keys([
        KeyBinding::new(
            "tab",
            gpui_kit::base::actions::SelectDown,
            Some("PopupMenu"),
        ),
        KeyBinding::new(
            "shift-tab",
            gpui_kit::base::actions::SelectUp,
            Some("PopupMenu"),
        ),
    ]);
    for context in ["DriftBrowser && !PopupMenu", "DriftComparisonFiles"] {
        cx.bind_keys([
            KeyBinding::new("home", CursorFirst, Some(context)),
            KeyBinding::new("g", CursorFirst, Some(context)),
            KeyBinding::new("end", CursorLast, Some(context)),
            KeyBinding::new("shift-g", CursorLast, Some(context)),
        ]);
    }
    for context in [
        "DriftLocalFilter",
        "DriftRemoteFilter",
        "DriftComparisonFilter",
    ] {
        cx.bind_keys([
            KeyBinding::new("down", FocusResults, Some(context)),
            KeyBinding::new("enter", FocusResults, Some(context)),
        ]);
    }
    cx.bind_keys([
        KeyBinding::new("p", TogglePreview, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new("c", CopyPreview, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new("ctrl-alt-f", ReturnFromFinder, Some("Drift && !PopupMenu")),
        KeyBinding::new("cmd-alt-f", ReturnFromFinder, Some("Drift && !PopupMenu")),
        KeyBinding::new("ctrl-alt-p", FocusPreview, Some("Drift && !PopupMenu")),
        KeyBinding::new("cmd-alt-p", FocusPreview, Some("Drift && !PopupMenu")),
        KeyBinding::new("f1", ShowHelp, Some("!PopupMenu")),
        KeyBinding::new("?", ShowHelp, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new("?", ShowHelp, Some("DriftComparisonFiles")),
        KeyBinding::new("?", ShowHelp, Some("DriftDiff")),
        KeyBinding::new("escape", Cancel, Some("DriftHelp")),
        KeyBinding::new("?", ShowHelp, Some("DriftHelp")),
        KeyBinding::new(
            "ctrl-enter",
            ConfirmSync,
            Some("DriftComparison && !PopupMenu"),
        ),
        KeyBinding::new(
            "cmd-enter",
            ConfirmSync,
            Some("DriftComparison && !PopupMenu"),
        ),
        KeyBinding::new("up", ScrollUp, Some("DriftHelp")),
        KeyBinding::new("down", ScrollDown, Some("DriftHelp")),
        KeyBinding::new("pageup", PageUp, Some("DriftHelp")),
        KeyBinding::new("pagedown", PageDown, Some("DriftHelp")),
        KeyBinding::new("home", CursorFirst, Some("DriftHelp")),
        KeyBinding::new("end", CursorLast, Some("DriftHelp")),
    ]);
    for context in ["DriftComparisonFiles", "DriftDiff"] {
        cx.bind_keys([
            KeyBinding::new("e", ToggleSyncErrors, Some(context)),
            KeyBinding::new("u", Upload, Some(context)),
            KeyBinding::new("d", Download, Some(context)),
            KeyBinding::new("shift-a", CycleAll, Some(context)),
            KeyBinding::new("n", NextFile, Some(context)),
            KeyBinding::new("p", PreviousFile, Some(context)),
            KeyBinding::new("r", Refresh, Some(context)),
            KeyBinding::new("i", ToggleIgnored, Some(context)),
            KeyBinding::new("s", SyncSelected, Some(context)),
            KeyBinding::new("shift-s", SyncAll, Some(context)),
            KeyBinding::new("tab", SwitchPane, Some(context)),
            KeyBinding::new("shift-tab", SwitchPane, Some(context)),
        ]);
    }
    cx.bind_keys([
        KeyBinding::new("left", DiffCaretLeft, Some("DriftDiff")),
        KeyBinding::new("right", DiffCaretRight, Some("DriftDiff")),
        KeyBinding::new("shift-left", DiffSelectLeft, Some("DriftDiff")),
        KeyBinding::new("shift-right", DiffSelectRight, Some("DriftDiff")),
        KeyBinding::new("shift-up", DiffSelectUp, Some("DriftDiff")),
        KeyBinding::new("shift-down", DiffSelectDown, Some("DriftDiff")),
        KeyBinding::new("shift-home", DiffSelectStart, Some("DriftDiff")),
        KeyBinding::new("shift-end", DiffSelectEnd, Some("DriftDiff")),
        KeyBinding::new("ctrl-a", DiffSelectAll, Some("DriftDiff")),
        KeyBinding::new("cmd-a", DiffSelectAll, Some("DriftDiff")),
        KeyBinding::new("up", ScrollUp, Some("DriftDiff")),
        KeyBinding::new("k", ScrollUp, Some("DriftDiff")),
        KeyBinding::new("down", ScrollDown, Some("DriftDiff")),
        KeyBinding::new("j", ScrollDown, Some("DriftDiff")),
        KeyBinding::new("pageup", PageUp, Some("DriftDiff")),
        KeyBinding::new("pagedown", PageDown, Some("DriftDiff")),
        KeyBinding::new("ctrl-u", HalfPageUp, Some("DriftDiff")),
        KeyBinding::new("ctrl-d", HalfPageDown, Some("DriftDiff")),
        KeyBinding::new("home", CursorFirst, Some("DriftDiff")),
        KeyBinding::new("g", CursorFirst, Some("DriftDiff")),
        KeyBinding::new("end", CursorLast, Some("DriftDiff")),
        KeyBinding::new("shift-g", CursorLast, Some("DriftDiff")),
        KeyBinding::new("]", NextHunk, Some("DriftDiff")),
        KeyBinding::new("[", PreviousHunk, Some("DriftDiff")),
        KeyBinding::new("enter", ExpandContext, Some("DriftDiff")),
        KeyBinding::new("l", ExpandContext, Some("DriftDiff")),
        KeyBinding::new("h", FoldContext, Some("DriftDiff")),
        KeyBinding::new("space", Activate, Some("DriftDiff")),
        KeyBinding::new("c", ToggleFolds, Some("DriftDiff")),
        KeyBinding::new("tab", SwitchPane, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new("shift-tab", SwitchPane, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new("shift-p", ShowProjects, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new("shift-h", ShowHosts, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new("@", ShowRemote, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new("/", FocusFilter, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new("f", FindFiles, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new(".", ToggleHidden, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new("shift-i", ToggleIgnored, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new("r", Refresh, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new("s", CompareMarked, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new("space", ToggleMark, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new("v", VisualRange, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new("shift-v", MarkAll, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new("*", InvertMarks, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new("escape", ClearMarks, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new("shift-up", RangeUp, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new("shift-down", RangeDown, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new(
            "shift-f10",
            OpenContextMenu,
            Some("DriftBrowser && !PopupMenu"),
        ),
        KeyBinding::new("menu", OpenContextMenu, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new("up", CursorUp, Some("DriftComparisonFiles")),
        KeyBinding::new("k", CursorUp, Some("DriftComparisonFiles")),
        KeyBinding::new("down", CursorDown, Some("DriftComparisonFiles")),
        KeyBinding::new("j", CursorDown, Some("DriftComparisonFiles")),
        KeyBinding::new("enter", Activate, Some("DriftComparisonFiles")),
        KeyBinding::new("space", Activate, Some("DriftComparisonFiles")),
        KeyBinding::new("alt-down", NextHunk, Some("DriftDiff")),
        KeyBinding::new("alt-up", PreviousHunk, Some("DriftDiff")),
        KeyBinding::new("ctrl-c", CopySelection, Some("DriftDiff")),
        KeyBinding::new("cmd-c", CopySelection, Some("DriftDiff")),
        KeyBinding::new("ctrl-alt-left", ResizePaneLeft, Some("Drift && !PopupMenu")),
        KeyBinding::new(
            "ctrl-alt-right",
            ResizePaneRight,
            Some("Drift && !PopupMenu"),
        ),
        KeyBinding::new("ctrl-alt-0", ResetPaneSizes, Some("Drift && !PopupMenu")),
        KeyBinding::new("ctrl-f", FocusFilter, Some("Drift && !PopupMenu")),
        KeyBinding::new("cmd-f", FocusFilter, Some("Drift && !PopupMenu")),
        KeyBinding::new("ctrl-shift-c", CopySelection, Some("Drift && !PopupMenu")),
        KeyBinding::new("cmd-shift-c", CopySelection, Some("Drift && !PopupMenu")),
        KeyBinding::new("f5", Refresh, Some("Drift && !PopupMenu")),
        KeyBinding::new("escape", Cancel, Some("Drift && !PopupMenu")),
        KeyBinding::new("ctrl-escape", CancelWork, Some("Drift && !PopupMenu")),
        KeyBinding::new("alt-left", GoBack, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new("alt-right", GoForward, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new("alt-up", GoUp, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new("backspace", GoUp, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new("left", Collapse, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new("h", Collapse, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new("up", CursorUp, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new("k", CursorUp, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new("down", CursorDown, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new("j", CursorDown, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new(
            "alt-enter",
            OpenDirectory,
            Some("DriftBrowser && !PopupMenu"),
        ),
        KeyBinding::new("enter", Activate, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new("right", Activate, Some("DriftBrowser && !PopupMenu")),
        KeyBinding::new("l", Activate, Some("DriftBrowser && !PopupMenu")),
    ]);
}
