use gpui_kit::{App, KeyBinding};

gpui_kit::actions!(
    drift,
    [
        FocusFilter,
        CopySelection,
        Refresh,
        Cancel,
        GoUp,
        GoBack,
        GoForward,
        CursorUp,
        CursorDown,
        CursorFirst,
        CursorLast,
        SwitchPane,
        ShowProjects,
        ShowHosts,
        ShowRemote,
        FindFiles,
        ToggleHidden,
        ToggleIgnored,
        NextFile,
        PreviousFile,
        SyncSelected,
        SyncAll,
        ConfirmSync,
        Activate,
        Collapse,
        OpenDirectory,
        NextHunk,
        CompareMarked,
        ToggleMark,
        VisualRange,
        MarkAll,
        InvertMarks,
        ClearMarks,
        RangeUp,
        RangeDown,
        PreviousHunk
    ]
);
pub fn bind_keys(cx: &mut App) {
    crate::hosts::bind_keys(cx);
    for context in ["DriftBrowser", "DriftComparisonFiles"] {
        cx.bind_keys([
            KeyBinding::new("home", CursorFirst, Some(context)),
            KeyBinding::new("g", CursorFirst, Some(context)),
            KeyBinding::new("end", CursorLast, Some(context)),
            KeyBinding::new("shift-g", CursorLast, Some(context)),
        ]);
    }
    for context in ["DriftComparisonFiles", "DriftDiff"] {
        cx.bind_keys([
            KeyBinding::new("n", NextFile, Some(context)),
            KeyBinding::new("p", PreviousFile, Some(context)),
            KeyBinding::new("r", Refresh, Some(context)),
            KeyBinding::new("i", ToggleIgnored, Some(context)),
            KeyBinding::new("s", SyncSelected, Some(context)),
            KeyBinding::new("shift-s", SyncAll, Some(context)),
            KeyBinding::new("ctrl-enter", ConfirmSync, Some(context)),
            KeyBinding::new("cmd-enter", ConfirmSync, Some(context)),
            KeyBinding::new("tab", SwitchPane, Some(context)),
            KeyBinding::new("shift-tab", SwitchPane, Some(context)),
        ]);
    }
    cx.bind_keys([
        KeyBinding::new("tab", SwitchPane, Some("DriftBrowser")),
        KeyBinding::new("shift-tab", SwitchPane, Some("DriftBrowser")),
        KeyBinding::new("shift-p", ShowProjects, Some("DriftBrowser")),
        KeyBinding::new("shift-h", ShowHosts, Some("DriftBrowser")),
        KeyBinding::new("@", ShowRemote, Some("DriftBrowser")),
        KeyBinding::new("/", FocusFilter, Some("DriftBrowser")),
        KeyBinding::new("f", FindFiles, Some("DriftBrowser")),
        KeyBinding::new(".", ToggleHidden, Some("DriftBrowser")),
        KeyBinding::new("shift-i", ToggleIgnored, Some("DriftBrowser")),
        KeyBinding::new("r", Refresh, Some("DriftBrowser")),
        KeyBinding::new("s", CompareMarked, Some("DriftBrowser")),
        KeyBinding::new("space", ToggleMark, Some("DriftBrowser")),
        KeyBinding::new("v", VisualRange, Some("DriftBrowser")),
        KeyBinding::new("shift-v", MarkAll, Some("DriftBrowser")),
        KeyBinding::new("*", InvertMarks, Some("DriftBrowser")),
        KeyBinding::new("escape", ClearMarks, Some("DriftBrowser")),
        KeyBinding::new("shift-up", RangeUp, Some("DriftBrowser")),
        KeyBinding::new("shift-down", RangeDown, Some("DriftBrowser")),
        KeyBinding::new("up", CursorUp, Some("DriftComparisonFiles")),
        KeyBinding::new("k", CursorUp, Some("DriftComparisonFiles")),
        KeyBinding::new("down", CursorDown, Some("DriftComparisonFiles")),
        KeyBinding::new("j", CursorDown, Some("DriftComparisonFiles")),
        KeyBinding::new("enter", Activate, Some("DriftComparisonFiles")),
        KeyBinding::new("space", Activate, Some("DriftComparisonFiles")),
        KeyBinding::new("alt-down", NextHunk, Some("DriftDiff")),
        KeyBinding::new("alt-up", PreviousHunk, Some("DriftDiff")),
        KeyBinding::new("ctrl-c", CopySelection, Some("DriftDiff")),
        KeyBinding::new("cmd-c", CopySelection, Some("DriftDiff")),
        KeyBinding::new("ctrl-f", FocusFilter, Some("Drift")),
        KeyBinding::new("cmd-f", FocusFilter, Some("Drift")),
        KeyBinding::new("ctrl-shift-c", CopySelection, Some("Drift")),
        KeyBinding::new("cmd-shift-c", CopySelection, Some("Drift")),
        KeyBinding::new("f5", Refresh, Some("Drift")),
        KeyBinding::new("escape", Cancel, Some("Drift")),
        KeyBinding::new("alt-left", GoBack, Some("DriftBrowser")),
        KeyBinding::new("alt-right", GoForward, Some("DriftBrowser")),
        KeyBinding::new("alt-up", GoUp, Some("DriftBrowser")),
        KeyBinding::new("backspace", GoUp, Some("DriftBrowser")),
        KeyBinding::new("left", Collapse, Some("DriftBrowser")),
        KeyBinding::new("h", Collapse, Some("DriftBrowser")),
        KeyBinding::new("up", CursorUp, Some("DriftBrowser")),
        KeyBinding::new("k", CursorUp, Some("DriftBrowser")),
        KeyBinding::new("down", CursorDown, Some("DriftBrowser")),
        KeyBinding::new("j", CursorDown, Some("DriftBrowser")),
        KeyBinding::new("alt-enter", OpenDirectory, Some("DriftBrowser")),
        KeyBinding::new("enter", Activate, Some("DriftBrowser")),
        KeyBinding::new("right", Activate, Some("DriftBrowser")),
        KeyBinding::new("l", Activate, Some("DriftBrowser")),
    ]);
}
